Issue #66 Detect if the firmware has reset.
Added two methods to find the state of the reset.

1. You can ask the firmware through the cs.reset read API.
- The firmware will respond back with the status of the reset bit.
- This bit will be cleared on the firmware side as soon as it has reset.

Below is an example of the firmware resetting because of a pulse

'''
>>> cs.reset
False
>>> cs.pulse = True
>>> cs.reset
True
'''

2. The API will detect the startup string on reading the uart. It will throw an exception if there was a reset.

'''
>>> from chipshouter import ChipSHOUTER
>>> cs = ChipSHOUTER('/dev/ttyUSB0')

>>> cs.reset
False
>>> cs.reset = True
>>> cs
Traceback (most recent call last):
...
  File "/home/pi/code/ChipSHOUTER-python/chipshouter/com_tools.py", line 97, in s_read
  raise IOError('Shouter has reset')
  IOError: Shouter has reset

>>> cs.reset
True
>>>
'''

com_tools.py
============
1. Made reading of the com port only return packed data. So the strings will be ignored.
2. Detect the start up string to throw and error if it is received so we know a reset occured during a command.
3. removed more prints.
4. Added IS_RESET as a new command.
5. Fixed the respons returing the wrong byte... caused the return to not handle the acks properly..
- It was the Elses that hid the issue.

chipshouter.py
==============
1. Added trigger_safe to the dict of vars to read in the cs.
2. Added reading of the reset to not return 0, but it will read from the shouter firmware what the answer is.